### PR TITLE
Adds test to the emojification

### PR DESCRIPTION
**Pull request by orta**
Adds some tests, and passes rubocop etc

### CODE REVIEW

**Comment by icanzilb** [comment]
@orta how do I run those on my machine? I can't seem to figure that out ... I get to run the tests but they all fail 😭

**Comment by orta** [comment]
either: `bundle exec rake spec` or 

```
bundle exec bacon spec/command/trunk/info_spec.rb spec/command/trunk/delete_spec.rb spec/command/trunk/register_spec.rb spec/command/trunk_spec.rb spec/command/trunk/deprecate_spec.rb spec/command/trunk/remove_owner_spec.rb spec/command/trunk/push_spec.rb spec/command/trunk/me_spec.rb spec/command/trunk/addowner_spec.rb
```

**Comment by icanzilb** [comment]
They still fail ... I guess I miss some "magic" config that makes those pass? 

```
Pod::Command::Trunk::Register
  CLAide
    ✓ registers it self
  ✓ should error if email is not supplied (2 ms)
  - should register user [FAILED]

Pod::Command::Trunk::Deprecate
  CLAide
    ✓ registers it self
  ✓ should error without a pod name
  ✓ should show information for a pod (79 ms)
  - should send the proper network request [FAILED]

etc... 
```

**Comment by orta** [comment]
Maybe try a different ruby version? Perhaps your local install is corrupt? I just cloned and ran it fresh

**Comment by icanzilb** [comment]
Tried with 2.2.0 and 2.1.0 ... gonna try with 2.3.1 and if that won't work I'll just merge it in anyway 😱

**Pull request merged**
